version: '3.8'

services:
  db_filmes:
    image: "postgres:16.1-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "filmes"
      POSTGRES_PASSWORD: "filmes"
      POSTGRES_DB: "filmes"